config/routes.rb
Heroappr1::Application.routes.draw do
  get "home", to:"home#index"
  get "welcome/index"
  post "welcome/login"
  get "welcome/index"

  root 'welcome#index'

  namespace :apps do
    resources :realtimes
  end

  get "wxs/io",  to: "wxs#auth"

  scope path: "/", via: :post, defaults: { format: 'xml'} do
    match 'wxs/io', to: 'wxs#reply_text', constraints: Weixin::Router.new(type: "text")

  end

  

end

app/models/message.rb
class Message < ActiveRecord::Base
	
end

app/models/receivemsg.rb
class Receivemsg < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(username, submitted_password)
    user = find_by_username(username)
    return nil if user.nil?
    #return user if user.has_password?(submitted_password)
    return user
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
 
	def set_locale
	  I18n.locale = params[:locale] || I18n.default_locale
	end
end

app/controllers/apps/realtimes_controller.rb
class Apps::RealtimesController < ApplicationController

	def index
		odr = params[:o]
		puts odr
		if odr== nil or odr.index('-') == -1
		  @messages = Message.all
		else
		  @messages = Message.where.order('#{odr} desc')
		end

		@total = Message.count
	end

	def new
		@messages = Message.new
	end

	def show
		
	end

	private
	def post_params
		params.require(:mesage).permit(:name,:code)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  skip_before_filter :verify_authenticity_token
  before_filter :check_weixin_legality

  def auth
    puts 'in auth method.'
  end

  def reply_text
    puts 'in reply text.'
    if params[:xml][:MsgType] == "text"
      render "echo", :formats => :xml
    end
  end

  private
  def check_weixin_legality
    array = [Rails.configuration.weixin_token, params[:timestamp], params[:nonce]].sort
    render :text => "Forbidden", :status => 403 if params[:signature] != Digest::SHA1.hexdigest(array.join)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.new
  end

  def login
    if request.post?
      @user = User.authenticate(params[:user][:username], params[:user][:password])
      if @user
        session[:user_id]= @user.id
        redirect_to(controller:'home')
      else
        flash[:notice] = 'Name or password failed.'
      end
    end
  end
  
end

app/controllers/wxs_controller.rb
class WxsController < ApplicationController

  skip_before_filter :verify_authenticity_token
  before_filter :check_weixin_legality

  def auth
    puts 'in auth method.'
    render :text => params[:echostr]
  end

  def reply_text
    puts 'in reply text.'

    puts weixin_xml.type
    puts weixin_xml.from_user
    puts weixin_xml.to_user
    puts weixin_xml.content
    render 'reply_text', status:200
    #puts params[:xml][:ToUserName]
    #puts params[:xml][:Content]
    #  render "reply_text"
  end

  private
  def check_weixin_legality
    #puts Rails.configuration.weixin_token
    #if params[:timestamp] != nil and params[:nonce]!= nil and params[:signature]!= nil
      array = [Rails.configuration.weixin_token, params[:timestamp], params[:nonce]].sort
      #puts Digest::SHA1.hexdigest(array.join)
      render text: "Forbidden", status: 403 if params[:signature] != Digest::SHA1.hexdigest(array.join)
    #end

    #array = [Rails.configuration.weixin_token, params[:timestamp], params[:nonce]].sort
    #render text: "Forbidden", status: 403 if params[:signature] != Digest::SHA1.hexdigest(array.join)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps/realtime_helper.rb
module Apps::RealtimeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wxs_helper.rb
module WxsHelper
end

app/views/apps/realtimes/index.html.erb
<%= javascript_include_tag "combody" %>

<%= render 'layouts/topnav' %>
<div id="body-content" class="row" style="margin-left:0;margin-right: 0;">

<%= render partial: 'layouts/leftside', locals:{ leftmenu: '/'+params[:controller] } %>

<div id="content-block" class="col col-xs-12 col-sm-11 col-md-10  col-lg-10">

<!--Breadcrumb-->
<ul class="breadcrumb">
  <li><%=link_to home_path do%> <%=I18n.t 'menu_home'%> <% end %></li>
  <li class="active"> <%=I18n.t 'realtime_breadcrumb_title'%> </li>
</ul>

<div class="navbar content-navbar navbar-sm" data-class-lg="navbar content-navbar"
     data-class-md="navbar content-navbar" data-class-sm="navbar content-navbar navbar-inverse"
     data-toggle="breakpoint">
  <button class="navbar-toggle nav-back" data-class-name="show_menu" data-target="#body-content"
          data-toggle="class" type="button">
    <i class="icon-list"></i>
  </button>

  <a class="navbar-brand" data-target="#top-nav .navbar-collapse" data-toggle="collapse">
    <i class="icon-briefcase"></i>
    <%=I18n.t 'realtime_toolbar_title'%>
  </a>

  <div class="navbar-btn pull-right">
    <a class="btn btn-default show-sm" data-target=".content-navbar .navbar-collapse" data-toggle="collapse">
      <i class="icon-filter icon-white"></i>
    </a>
    <%= link_to new_apps_realtime_path, class: 'btn btn-primary' do %>
        <i class="icon-plus"></i> <span><%=t('realtime_toolbar_add')%></span>
    <% end %>
  </div>

  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li class="dropdown bookmarks">
        <a id="drop-bookmark" class="dropdown-toggle" href="#" data-toggle="dropdown" role="button"
           title="Bookmark">
          <i class="icon-book"></i>
          	<%=t('global_bookmark')%>
          <span class="caret"></span>
        </a>
        <ul id="bookmark-menu" class="dropdown-menu" role="menu" style="max-height: 508px;">
          <li>
            <a class="mute"><%=t('global_bookmark_no')%></a>
          </li>
          <li class="divider"></li>
          <li class="add-bookmark">
            <a id="a_id_addBookmark" href="#">
              <i class="icon-plus"></i>
              <%=t('global_bookmark_new')%>
            </a>

            <div id="div_id_addBookmark" class="popover right">
              <div class="arrow"></div>
              <div class="popover-inner">
                <h3 class="popover-title"> Save current page as Bookmark </h3>

                <div class="popover-content">
                  <form id="bookmark_form" action="/app/continent/bookmark/" method="post">
                    <input type="hidden" value="jzyr1GSvTWVNPfdcdPlqY2DzXYNs9RP3" name="csrfmiddlewaretoken">
                    <input type="hidden" value="_cols=id.name&o=-name" name="query">
                    <input type="text" placeholder="Enter bookmark title…" name="title">
                    <button class="btn btn-success" data-loading-text="Waiting..." type="submit">Save Bookmark</button>
                  </form>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </li>
    </ul>


    <form class="navbar-form pull-left" method="get" action="">
      <div class="input-group search-group">
        <input id="searchbar" class="form-control" type="text" placeholder="Search" value="" name="_q_">
            <span class="input-group-btn">
            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" type="submit">
              <i class="icon-search"></i>
            </button>
            </span>
      </div>
    </form>

  </div>
</div>

<div class="content-toolbar btn-toolbar pull-right clearfix">
  <!--List right buttons-->
  <%= render 'layouts/list_export' %>
  <%= render 'layouts/list_colums' %>
  <%= render 'layouts/list_layoutbuttons' %>
</div>

<ul class="pagination pagination-small pagination-left pagination-inline">
  <li>
    <span>
      <% if @total > 1 %>
        <b><%= @total %></b> <%=t('realtime_title')%>
      <% else %>
        <b><%= @total %></b> <%=t('realtime_title')%>
      <% end %>
      </span>
  </li>
</ul>
<form id="changelist-form" method="post" action="">
  <div class="results">
    <% if @total == 0 %>
        <p class="well"><%= t('global_result_empty')%></p>
    <% else %>
        <table class="table table-bordered table-striped table-hover">
          <thead>
          <tr>
            <th class="action-checkbox-column" scope="col">
              <input id="action-toggle" type="checkbox">
            </th>
            <th class="sortable sorted ascending" scope="col">
              <div class="pull-right">
                <a class="toggle" href="?o=-name">
                  <i class="icon-sort-up"></i>
                </a>
              </div>
              <div class="dropdown pull-left">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown"> Name </a>

                <ul class="dropdown-menu" role="menu">
                  <li class="active">
                    <a class="active" href="?o=name">
                      <i class="icon-caret-up"></i>
                      Sort ASC
                    </a>
                  </li>
                  <li>
                    <a class="active" href="?o=-name">
                      <i class="icon-caret-down"></i>
                      Sort DESC
                    </a>
                  </li>
                  <li>
                    <a class="active" href="?o=">
                      <i class="icon-remove"></i>
                      Cancel Sort
                    </a>
                  </li>
                </ul>
              </div>
            </th>
            <th scope="col"></th>
          </tr>
          </thead>
          <tbody>
          <% @messages.each do |message| %>
              <tr class="row1">
                <td class="action-checkbox">
                  <input class="action-select" type="checkbox" value="4" name="_selected_action">
                </td>
                <td>
                  <%= link_to edit_apps_realtime_path(message) do %><%= message.name %>
                  <% end %>
                  <!--<a href="/app/continent/4/update/">Koodoo</a>-->
                </td>
                <td>
                  <div class="dropdown related_menu pull-right">
                    <a class="relate_menu dropdown-toggle" data-toggle="dropdown" title="Related Objects">
                      <i class="icon icon-list"></i>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                      <li class="with_menu_btn">
                        <%= link_to edit_apps_realtime_path(message) do %>
                            <i class="icon icon-th-list"></i>
                            comment
                        <% end %>
                        <!--<a title="module" href="/app/module/?_rel_continent__id__exact=4">-->
                        <!--<i class="icon icon-th-list"></i>-->
                        <!--comment-->
                        <!--</a>-->
                        <a class="add_link dropdown-menu-btn"
                           href="/app/module/add/?_rel_continent__id__exact=4">
                          <i class="icon icon-plus pull-right"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </td>
              </tr>
          <% end %>
          <!--end of each-->
          </tbody>
        </table>
    <% end %>
    <!--end of if-->
  </div>

  <div class="form-actions well well-sm">
    <input id="action" type="hidden" value="" name="action">
    <input id="select-across" type="hidden" value="0" name="select_across">

    <div class="btn-group clearfix dropup">
      <a class="dropdown-toggle btn btn-success" href="#" data-toggle="dropdown">
        <i class="icon-wrench icon-white"></i>
        <span class="action-counter">0 of 0 selected</span>
        <span class="all" style="display: none;">1 selected</span>
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" aria-labelledby="dLabel" role="menu">
        <li>
          <a onclick="$.do_action('delete_selected');">
            <i class="icon-remove"></i>
            Delete selected continents
          </a>
        </li>
      </ul>
    </div>
    <script type="text/javascript">
        var _actions_icnt = <%=@total%>;
    </script>
  </div>
</form>
</div>

</div>

<%= render 'layouts/footer' %>


app/views/home/index.html.erb
<%= javascript_include_tag "combody"%>


<%= render 'layouts/topnav'%>

<div id="body-content" class="row" style="margin-left:0;margin-right: 0;">

  <%= render partial: 'layouts/leftside', locals:{leftmenu: '/'+ params[:controller] }%>

  <div id="content-block" class="col col-xs-12 col-sm-11 col-md-10  col-lg-10">
    <div class="navbar content-navbar" data-class-lg="navbar content-navbar"
         data-class-md="navbar content-navbar" data-class-sm="navbar content-navbar navbar-inverse"
         data-toggle="breakpoint">
      <!--<button class="navbar-toggle nav-back navbar-left" data-class-name="show_menu" data-target="#body-content"-->
              <!--data-toggle="class" type="button">-->
        <!--<i class="icon-list"></i>-->
      <!--</button>-->

      <div class="navbar-header">
        <button class="navbar-toggle collapsed" data-class-name="show_menu" data-target="#body-content" data-toggle="class" type="button">
          <span class="sr-only">Toggle navigation</span>
          <i class="icon-list"></i>
        </button>
        <a class="navbar-brand" data-target="#top-nav .navbar-collapse" data-toggle="collapse">
          <i class="icon-dashboard"></i>
          Main Dashboard
        </a>
      </div>

      <!--<button class="navbar-btn btn btn-primary pull-right"><i class="icon-plus"></i>-->
        <!--<span>Add Widget</span></button>-->

      <div class="navbar-btn pull-right">
        <a class="btn btn-primary" href="#" title="Add Widget">
          <i class="icon-plus"></i>
          <span>Add Widget</span>
        </a>
      </div>
    </div>
  </div>
</div>

<%= render 'layouts/footer'%>

app/views/layouts/_footer.html.erb
<div id="footer">
  <hr>
  <footer class="text-center">
    <p>&copy; my-company.inc 2013</p>
  </footer>
</div>

app/views/layouts/_leftside.html.erb
<div id="left-side" class="col col-sm-1 col-md-2 col-lg-2">

  <ul class="well nav nav-pills nav-stacked nav-sitemenu hidden-sm">
    <% if leftmenu == home_path %>
    <li class="active">
      <% else %>
    <li>
    <% end %>
        <%= link_to home_path do %><i class="icon-home"></i> <%= I18n.t 'menu_home'%> <% end %>
    </li>

    <li class="nav-header active"> Message </li>
    <li <%= leftmenu == apps_realtimes_path ? 'class=active' : '' %> >
      <!-- <a href="/realtime/index"> <i class="icon-fixed-width icon-briefcase"></i> Projects</a> -->
       <%= link_to apps_realtimes_path do %> <i class="icon-fixed-width icon-briefcase"></i> <%= I18n.t 'menu_message'%>
       <% end %>
    </li>
    <li <%= leftmenu == '' ? 'class=active' : '' %> >
      <a href="/heroapp/html/bug/bug.html"> <i class="icon-fixed-width icon-bug"></i> <%= I18n.t 'menu_eventsend'%></a>
    </li>
    <li class="nav-header active"> Auto</li>
    <li <%= leftmenu == ''? 'class=active' : '' %> >
      <a href="/app/continent/"> <i class="icon-fixed-width icon-laptop"></i> <%= I18n.t 'menu_contact'%></a>
    </li>
    <li <%= leftmenu == '' ? 'class=active' : '' %> >
      <a href="/app/continent/"> <i class="icon-fixed-width icon-lock"></i> <%= I18n.t 'menu_material'%></a>
    </li>
    <li <%= leftmenu == '' ? 'class=active' : '' %> >
      <a href="/app/continent/"> <i class="icon-fixed-width icon-user"></i> <%= I18n.t 'menu_autoreplay'%></a>
    </li>
    <li class="nav-header active"> System</li>
    <li <%= leftmenu == ''? 'class=active' : '' %> >
      <a href="/app/continent/"> <i class="icon-fixed-width icon-cog"></i> <%= I18n.t 'menu_config'%></a>
    </li>
  </ul>

  <ul class="well nav nav-pills nav-stacked nav-sitemenu visible-sm">
    <li class="app_menu">
      <a href="#"><i class="icon-fixed-width icon-home"></i></a>
    </li>

    <li class="app_menu">
      <a class="section dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="icon-fixed-width icon-comments-alt"></i>
      </a>

      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li>
          <%= link_to  do%> <i class="icon-fixed-width icon-briefcase"></i> <%= I18n.t 'menu_message'%> <%end%>
        </li>
        <li>
          <a href="/app/module/"><i class="icon-fixed-width icon-bug"></i> <%= I18n.t 'menu_eventsend'%> </a>
        </li>
      </ul>
    </li>

    <li class="app_menu">
      <a href="#" class="section dropdown-toggle" data-toggle="dropdown">
        <i class="icon-fixed-width icon-cloud-download"></i>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                <li>
          <a href="/app/module/"><i class="icon-fixed-width icon-bug"></i> <%= I18n.t 'menu_contact'%> </a>
        </li>
        <li>
          <a href="/app/module/"><i class="icon-fixed-width icon-bug"></i> <%= I18n.t 'menu_material'%> </a>
        </li>
        <li>
          <a href="/app/module/"><i class="icon-fixed-width icon-bug"></i> <%= I18n.t 'menu_autoreplay'%> </a>
        </li>
      </ul>
    </li>

    <li class="app_menu">
      <a href="#" class="section dropdown-toggle" data-toggle="dropdown">
        <i class="icon-fixed-width icon-cogs"></i>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li>
          <a href="/app/module/"><i class="icon-fixed-width icon-bug"></i> <%= I18n.t 'menu_config'%> </a>
        </li>
      </ul>
    </li>
  </ul>
</div>

app/views/layouts/_list_colums.html.erb
<div class="btn-group">
  <a class="dropdown-toggle btn btn-default btn-small" href="#" data-toggle="dropdown">
    <i class="icon-list-alt"></i>
    Columes
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu model_fields pull-right" aria-labelledby="dLabel" role="menu">
    <li>
      <a href="?">
        <i class="icon-refresh"></i>
        Restore Selected
      </a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="?_cols=id.name">
        <i class="icon-blank"></i>
        ID
      </a>
    </li>
    <li>
      <a href="?_cols=">
        <i class="icon-check"></i>
        name
      </a>
    </li>
    <li>
      <a href="?_cols=name.order">
        <i class="icon-blank"></i>
        order
      </a>
    </li>
  </ul>
</div>

app/views/layouts/_list_export.html.erb
<div class="btn-group export">
  <a class="dropdown-toggle btn btn-default btn-small" href="#" data-toggle="dropdown">
    <i class="icon-share"></i>
    <%=t('global_export')%>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" aria-labelledby="dLabel" role="menu">
    <li>
      <a data-target="#export-modal-xls" data-toggle="modal">
        <i class="icon-circle-arrow-down"></i>
        <%=t('global_export_excel')%>
      </a>
    </li>
    <li>
      <a data-target="#export-modal-csv" data-toggle="modal">
        <i class="icon-circle-arrow-down"></i>
        Export CSV
      </a>
    </li>
    <li>
      <a data-target="#export-modal-xml" data-toggle="modal">
        <i class="icon-circle-arrow-down"></i>
        Export XML
      </a>
    </li>
    <li>
      <a data-target="#export-modal-json" data-toggle="modal">
        <i class="icon-circle-arrow-down"></i>
        Export JSON
      </a>
    </li>
  </ul>
  <div id="export-modal-xls" class="modal fade" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="" method="get">
          <div class="modal-header">
            <button class="close" aria-hidden="true" data-dismiss="modal" type="button">&times;</button>
            <h4 class="modal-title">Export Excel</h4>
          </div>
          <div class="modal-body">
            <input type="hidden" value="export" name="_do_">
            <input type="hidden" value="xls" name="export_type">
            <label class="checkbox">
              <input type="checkbox" value="on" checked="checked" name="export_xls_header">
              Export with table header.
            </label>
            <label class="checkbox">
              <input type="checkbox" value="on" name="all">
              Export all datas.
            </label>
          </div>
          <div class="modal-footer">
            <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
            <button class="btn btn-success" type="submit">
              <i class="icon-share"></i>
              Export
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div id="export-modal-csv" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="" method="get">
          <div class="modal-header">
            <button class="close" aria-hidden="true" data-dismiss="modal" type="button">&times;</button>
            <h4 class="modal-title">Export CSV</h4>
          </div>
          <div class="modal-body">
            <input type="hidden" value="export" name="_do_">
            <input type="hidden" value="csv" name="export_type">
            <label class="checkbox">
              <input type="checkbox" value="on" checked="checked" name="export_csv_header">
              Export with table header.
            </label>
            <label class="checkbox">
              <input type="checkbox" value="on" name="all">
              Export all datas.
            </label>
          </div>
          <div class="modal-footer">
            <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
            <button class="btn btn-success" type="submit">
              <i class="icon-share"></i>
              Export
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div id="export-modal-xml" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="" method="get">
          <div class="modal-header">
            <button class="close" aria-hidden="true" data-dismiss="modal" type="button">&times;</button>
            <h4 class="modal-title">Export XML</h4>
          </div>
          <div class="modal-body">
            <input type="hidden" value="export" name="_do_">
            <input type="hidden" value="xml" name="export_type">
            <label class="checkbox">
              <input type="checkbox" value="on" checked="checked" name="export_xml_format">
              Export with format.
            </label>
            <label class="checkbox">
              <input type="checkbox" value="on" name="all">
              Export all datas.
            </label>
          </div>
          <div class="modal-footer">
            <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
            <button class="btn btn-success" type="submit">
              <i class="icon-share"></i>
              Export
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div id="export-modal-json" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="" method="get">
          <div class="modal-header">
            <button class="close" aria-hidden="true" data-dismiss="modal" type="button">&times;</button>
            <h4 class="modal-title">Export JSON</h4>
          </div>
          <div class="modal-body">
            <input type="hidden" value="export" name="_do_">
            <input type="hidden" value="json" name="export_type">
            <label class="checkbox">
              <input type="checkbox" value="on" checked="checked" name="export_json_format">
              Export with format.
            </label>
            <label class="checkbox">
              <input type="checkbox" value="on" name="all">
              Export all datas.
            </label>
          </div>
          <div class="modal-footer">
            <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
            <button class="btn btn-success" type="submit">
              <i class="icon-share"></i>
              Export
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_list_layoutbuttons.erb
<div class="btn-group layout-btns" data-toggle="buttons">
  <label class="btn btn-default btn-small layout-normal active">
    <input type="radio"> <i class="icon-th-large"></i>
  </label>
  <label class="btn btn-default btn-small layout-normal layout-condensed">
    <input type="radio"> <i class="icon-th"></i>
  </label>
</div>
<div class="btn-group layout-btns" data-toggle="buttons">
  <label class="btn btn-default btn-small layout-full">
    <input type="checkbox"> <i class="icon-fullscreen"></i>
  </label>
</div>

app/views/layouts/_topnav.html.erb
<div id="top-nav" class="navbar navbar-inverse navbar-fixed-top " role="navigation">

  <button class="navbar-toggle" data-target="#top-nav .navbar-collapse" data-toggle="collapse" type="button">
    <span class="icon-list"></span>
  </button>

  <a class="navbar-brand" href="#"><%= I18n.t 'app_title'%></a>

  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown g-add">
        <a class="dropdown-toggle" href="#" data-toggle="dropdown" role="button">
          <i class="icon-plus"></i>
          Add
          <span class="caret"></span>
        </a>
        <ul id="g-add-menu" class="dropdown-menu" role="menu" style="max-height: 397px;">
          <li>
            <a href="/reversion/version/add/"><i class="icon-plus"></i> Add Version</a>
          </li>
        </ul>
      </li>

      <li class="dropdown">
        <a class="dropdown-toggle" href="#" data-toggle="dropdown" role="button">
          <strong>Welcome, admin</strong>
          <span class="caret"></span>
        </a>
        <ul id="g-account-menu" class="dropdown-menu" role="menu" style="max-height: 397px;">
          <li>
            <a href="/account/password/"><i class="icon-key"></i></i> Change Password
            </a>
          </li>
        </ul>
      </li>
      <li class="">
        <a href="/logout/">Log out</a>
      </li>
    </ul>
    <form id="g-search" class="top-search-form navbar-form pull-left" method="get">
      <div class="input-group">
        <input type="text" class="form-control">

        <div class="input-group-btn">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <i class="icon-search"></i> Search <span class="caret"></span>
          </button>
          <ul class="dropdown-menu pull-right">
            <li><a href="#"><i class="icon-search"></i> Search Bug</a></li>
            <li><a href="#"><i class="icon-search"></i> Search Project</a></li>
          </ul>
        </div>
        <!-- /btn-group -->
      </div>
    </form>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>WX-Hero</title>
  <meta content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" name="viewport">
  <meta content="" name="description">
  <meta content="" name="author">
  <meta content="NONE,NOARCHIVE" name="robots">
  <%= csrf_meta_tags %>


  <%= stylesheet_link_tag "site", media: "screen" %>
  <%= stylesheet_link_tag "font-awesome/css/font-awesome", media: "screen" %>




  <%= javascript_include_tag "site" %>

  <!-- <%= javascript_include_tag "bootstrap/js/bootstrap", "data-turbolinks-track" => true %>
   -->

</head>
<body>
	<%= yield %>        
</body>
</html>

app/views/wxs/echo.xml.erb
<xml>
    <ToUserName><![CDATA[ <%= params[:xml][:ToUserName] %> ]]></ToUserName>
    <FromUserName><![CDATA[<%= params[:xml][:FromUserName] %>]]></FromUserName>
    <CreateTime><%= Time.now.to_i %></CreateTime>
    <MsgType><![CDATA[text]]></MsgType>
    <Content><![CDATA[你是说：<%= params[:xml][:Content] %>？]]></Content>
    <FuncFlag>0</FuncFlag>
</xml>